# Generated by Django 3.2.9 on 2022-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPapersData',
            fields=[
                ('keySourceId', models.AutoField(primary_key=True, serialize=False)),
                ('paperTitle', models.CharField(max_length=255, verbose_name='Paper Title')),
                ('paperFile', models.FileField(upload_to='keypapers/', verbose_name='Paper File')),
            ],
            options={
                'verbose_name': 'Key Papers',
                'verbose_name_plural': 'Key Papers',
            },
        ),
        migrations.CreateModel(
            name='KeyWebsitesData',
            fields=[
                ('keySourceId', models.AutoField(primary_key=True, serialize=False)),
                ('websiteName', models.CharField(max_length=255, verbose_name='Website Name')),
                ('websiteUrl', models.URLField(max_length=255, verbose_name='Website URL')),
            ],
            options={
                'verbose_name': 'Key Websites',
                'verbose_name_plural': 'Key Websites',
            },
        ),
    ]
