# Generated by Django 3.2.9 on 2022-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsData',
            fields=[
                ('submitId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('firstName', models.CharField(max_length=100, verbose_name='FirstName')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us Data',
                'verbose_name_plural': 'Contact Us Data',
            },
        ),
    ]
