# Generated by Django 3.2.9 on 2022-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusdata',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Title'),
        ),
    ]
