# Generated by Django 3.2.9 on 2022-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitData',
            fields=[
                ('submitId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('submitFile', models.FileField(upload_to='submitdata/')),
            ],
            options={
                'verbose_name': 'Submit Data',
                'verbose_name_plural': 'Submit Data',
            },
        ),
    ]
