# Generated by Django 3.2.9 on 2021-12-15 08:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edgeId', models.AutoField(primary_key=True, serialize=False)),
                ('edgeTypeName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Edge',
                'verbose_name_plural': 'Edges',
            },
        ),
        migrations.CreateModel(
            name='NeuronClass',
            fields=[
                ('neuronClassId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Neuron Class',
                'verbose_name_plural': 'Neuron Classes',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('neuronId', models.AutoField(primary_key=True, serialize=False)),
                ('neuronName', models.CharField(max_length=10, unique=True)),
                ('className', models.ForeignKey(blank=True, db_column='className', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.neuronclass', to_field='className')),
            ],
            options={
                'verbose_name': 'Neuron',
                'verbose_name_plural': 'Neurons',
            },
        ),
        migrations.CreateModel(
            name='Connectome',
            fields=[
                ('connectomeId', models.AutoField(primary_key=True, serialize=False)),
                ('numOfEdges', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('edgeTypeName', models.ForeignKey(blank=True, db_column='edgeTypeName', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge', to_field='edgeTypeName')),
                ('neuronReceiver', models.ForeignKey(db_column='neuronReceiver', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_receptor', to='neurons.neuron', to_field='neuronName')),
                ('neuronSender', models.ForeignKey(db_column='neuronSender', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_transporter', to='neurons.neuron', to_field='neuronName')),
            ],
            options={
                'verbose_name': 'Connectome',
                'verbose_name_plural': 'Connectomes',
            },
        ),
    ]
