# Generated by Django 3.2.9 on 2022-05-04 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edgeId', models.AutoField(primary_key=True, serialize=False, verbose_name='Edge Id')),
                ('edgeTypeName', models.CharField(max_length=10, unique=True, verbose_name='Edge Type Name')),
            ],
            options={
                'verbose_name': 'Edge',
                'verbose_name_plural': 'Edges',
            },
        ),
        migrations.CreateModel(
            name='NeuronClass',
            fields=[
                ('neuronClassId', models.AutoField(primary_key=True, serialize=False, verbose_name='Class Id')),
                ('className', models.CharField(max_length=10, unique=True, verbose_name='Class Name')),
            ],
            options={
                'verbose_name': 'Neuron Class',
                'verbose_name_plural': 'Neuron Classes',
            },
        ),
        migrations.CreateModel(
            name='NeuronType',
            fields=[
                ('neuronTypeId', models.AutoField(primary_key=True, serialize=False, verbose_name='Neuron Type Id')),
                ('neuronTypeName', models.CharField(max_length=100, unique=True, verbose_name='Neuron Type Name')),
            ],
            options={
                'verbose_name': 'Neuron Type',
                'verbose_name_plural': 'Neuron Types',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('neuronId', models.AutoField(primary_key=True, serialize=False, verbose_name='Neuron Id')),
                ('neuronName', models.CharField(max_length=10, unique=True, verbose_name='Neuron Name')),
                ('className', models.ForeignKey(blank=True, db_column='className', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.neuronclass', to_field='className', verbose_name='Class Name')),
                ('neuronTypeName', models.ForeignKey(blank=True, db_column='neuronTypeName', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.neurontype', to_field='neuronTypeName', verbose_name='Neuron Type Name')),
            ],
            options={
                'verbose_name': 'Neuron',
                'verbose_name_plural': 'Neurons',
            },
        ),
        migrations.CreateModel(
            name='Connectome',
            fields=[
                ('connectomeId', models.AutoField(primary_key=True, serialize=False, verbose_name='Connectome Id')),
                ('numOfEdges', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Edges')),
                ('edgeTypeName', models.ForeignKey(blank=True, db_column='edgeTypeName', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge', to_field='edgeTypeName', verbose_name='Edge Type Name')),
                ('neuronReceiver', models.ForeignKey(db_column='neuronReceiver', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_receptor', to='neurons.neuron', to_field='neuronName', verbose_name='Neuron Receiver')),
                ('neuronSender', models.ForeignKey(db_column='neuronSender', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_transporter', to='neurons.neuron', to_field='neuronName', verbose_name='Neuron Sender')),
            ],
            options={
                'verbose_name': 'Connectome',
                'verbose_name_plural': 'Connectomes',
            },
        ),
    ]
