# Generated by Django 3.2.9 on 2021-11-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('neuronEdgeId', models.AutoField(primary_key=True, serialize=False)),
                ('neuronEdgeType', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Edge',
                'verbose_name_plural': 'Edges',
            },
        ),
        migrations.CreateModel(
            name='NeuronClass',
            fields=[
                ('neuronClassId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Neuron Class',
                'verbose_name_plural': 'Neuron Classes',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('neuronId', models.AutoField(primary_key=True, serialize=False)),
                ('neuronName', models.CharField(max_length=10)),
                ('neuronClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurons.neuronclass')),
            ],
            options={
                'verbose_name': 'Neuron',
                'verbose_name_plural': 'Neurons',
            },
        ),
        migrations.CreateModel(
            name='Connectome',
            fields=[
                ('neuronConnId', models.AutoField(primary_key=True, serialize=False)),
                ('neuronConnNum', models.IntegerField(default=1)),
                ('neuronEdgeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge')),
                ('neuronReceiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n_receptor', to='neurons.neuron')),
                ('neuronSender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n_transporter', to='neurons.neuron')),
            ],
            options={
                'verbose_name': 'Connectome',
                'verbose_name_plural': 'Connectomes',
            },
        ),
    ]
