# Generated by Django 3.2.9 on 2022-01-28 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neurons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectome',
            name='connectomeId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Connectome Id'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='edgeTypeName',
            field=models.ForeignKey(blank=True, db_column='edgeTypeName', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge', to_field='edgeTypeName', verbose_name='Edge Type Name'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronReceiver',
            field=models.ForeignKey(db_column='neuronReceiver', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_receptor', to='neurons.neuron', to_field='neuronName', verbose_name='Neuron Receiver'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronSender',
            field=models.ForeignKey(db_column='neuronSender', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_transporter', to='neurons.neuron', to_field='neuronName', verbose_name='Neuron Sender'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='numOfEdges',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Edges'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='edgeId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Edge Id'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='edgeTypeName',
            field=models.CharField(max_length=10, unique=True, verbose_name='Edge Type Name'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='className',
            field=models.ForeignKey(blank=True, db_column='className', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.neuronclass', to_field='className', verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='neuronId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Neuron Id'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='neuronName',
            field=models.CharField(max_length=10, unique=True, verbose_name='Neuron Name'),
        ),
        migrations.AlterField(
            model_name='neuronclass',
            name='className',
            field=models.CharField(max_length=10, unique=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='neuronclass',
            name='neuronClassId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Class Id'),
        ),
    ]
