# Generated by Django 3.2.9 on 2021-11-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neurons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectome',
            name='neuronEdgeId',
            field=models.ForeignKey(db_column='neuronEdgeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronReceiver',
            field=models.ForeignKey(db_column='neuronReceiver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n_receptor', to='neurons.neuron'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronSender',
            field=models.ForeignKey(db_column='neuronSender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='n_transporter', to='neurons.neuron'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='neuronClassId',
            field=models.ForeignKey(db_column='neuronClassId', on_delete=django.db.models.deletion.CASCADE, to='neurons.neuronclass'),
        ),
    ]
