# Generated by Django 3.2.9 on 2021-11-30 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neurons', '0002_auto_20211118_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectome',
            name='neuronConnNum',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronEdgeId',
            field=models.ForeignKey(blank=True, db_column='neuronEdgeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.edge'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronReceiver',
            field=models.ForeignKey(db_column='neuronReceiver', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_receptor', to='neurons.neuron'),
        ),
        migrations.AlterField(
            model_name='connectome',
            name='neuronSender',
            field=models.ForeignKey(db_column='neuronSender', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='n_transporter', to='neurons.neuron'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='neuronEdgeType',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='neuronClassId',
            field=models.ForeignKey(blank=True, db_column='neuronClassId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neurons.neuronclass'),
        ),
        migrations.AlterField(
            model_name='neuron',
            name='neuronName',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='neuronclass',
            name='className',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
